name: octo_split
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  google_fonts: ^6.1.0
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1 # Manage permissions
  lucide_icons: ^0.257.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  flutter_contacts: ^1.1.9+2
  share_plus: ^10.1.4
  screenshot: ^3.0.0
  image_picker: ^1.1.2
  flutter_native_contact_picker: ^0.0.10
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - images/

